### ISSUE TITLE
Return Value Strangenesses

### ISSUE THREAD

**Issue by unparalleled-js** [Shard-Labs/starknet-devnet#127] opened 2022-06-14 00:07 UTC
I am noticing some odd behaviors with return values as of recently where the length of return arguments is included. Here are the scenarios I have tried:

```cairo
@external
func get_array{
        syscall_ptr : felt*, pedersen_ptr : HashBuiltin*,
        range_check_ptr}() -> (arr_len: felt, arr: felt*):
    const ARRAY_SIZE = 3
    let (ptr) = alloc()
    assert [ptr] = 1
    assert [ptr + 1] = 2
    assert [ptr + 2] = 3
    let (current_count) = array_get_counter.read()
    array_get_counter.write(current_count + 1)
    return (ARRAY_SIZE, ptr)
end

@view
func view_array{
        syscall_ptr : felt*, pedersen_ptr : HashBuiltin*,
        range_check_ptr}() -> (arr_len: felt, arr: felt*):
    const ARRAY_SIZE = 3
    let (ptr) = alloc()
    assert [ptr] = 1
    assert [ptr + 1] = 2
    assert [ptr + 2] = 3
    return (ARRAY_SIZE, ptr)
end
```

| method  | client      | result          |
|:-----------:|:-----------:|:---------------:|
| @external | normal   | [3, 1, 2, 3]
| @external | account | [4, 3, 1, 2, 3]
| @view      | normal   | [3, 1, 2, 3]    |

**Comment by badurinantun** [comment] 2022-06-14 06:59
Isn't this because account can have multiple calls?

**Comment by 0xSidius** [comment] 2022-06-14 07:15
For further reference:

![unknown (1)](https://user-images.githubusercontent.com/100469911/173516505-3c011a49-e4ac-4e41-a1b6-1bd23b21630d.png)

**Comment by FabijanC** [comment] 2022-06-14 08:17
@unparalleled-js How does this differ from responses you get from alpha-goerli?

**Comment by ca11ab1e** [comment] 2022-06-14 13:41
If I did it correctly, I got that result from alpha-goerli ([contract](https://goerli.voyager.online/contract/0x015ce17df625e284ce1ec7299b178948008b304ed30daf7958c520a2dcb89cde#readContract)):

| methode | client | result |
| --- | --- | --- |
| @view | normal | [1, 2, 3] |

**Comment by 0xSidius** [comment] 2022-06-14 14:18
@unparalleled-js if it's any help
![image](https://user-images.githubusercontent.com/100469911/173599995-7745c7cc-26fc-4c40-a849-6bd27e5f2361.png)

**Comment by FabijanC** [comment] 2022-06-17 07:48
@unparalleled-js have you been able to compare with output from alpha-goerli?

**Comment by ca11ab1e** [comment] 2022-06-18 14:36
I finally got a comparison with alpha-goerli. Returned data are identical to the devnet:
```bash
$ starknet get_transaction_receipt --hash 0x552334e3dfb31d87d62eb9c1483551c30f03c91e5aa7af376df030646c21123 --network alpha-goerli | jq '.events'
```
```json
[
  {
    "data": [
      "0x552334e3dfb31d87d62eb9c1483551c30f03c91e5aa7af376df030646c21123",
      "0x4",
      "0x3",
      "0x1",
      "0x2",
      "0x3"
    ],
    "from_address": "0x7583599f20b8c0e94831494659f1ffc0858f4d41c2813aef0bc542f2487c2df",
    "keys": [
      "0x5ad857f66a5b55f1301ff1ed7e098ac6d4433148f0b72ebc4a2945ab85ad53"
    ]
  }
]
```

**Comment by ca11ab1e** [comment] 2022-06-18 16:26
I adapted the test contract to generate an array with 10 elements.
Result: `[11 10 1 2 3 4 5 6 7 8 9 0]`

[tx](https://goerli.voyager.online/tx/0x67411b96d1b4cca009c7ae16cad46be17aa21000de8c4431b6f5c227f6e7aae#events) details:
```bash
$ starknet get_transaction_receipt --hash 0x67411b96d1b4cca009c7ae16cad46be17aa21000de8c4431b6f5c227f6e7aae --network alpha-goerli | jq '.events[0].data'
```
```json
[
  "0x67411b96d1b4cca009c7ae16cad46be17aa21000de8c4431b6f5c227f6e7aae",
  "0xb",
  "0xa",
  "0x1",
  "0x2",
  "0x3",
  "0x4",
  "0x5",
  "0x6",
  "0x7",
  "0x8",
  "0x9",
  "0x0"
]
```

**Comment by ca11ab1e** [comment] 2022-06-18 17:07
In a diff of the same contract compiled with Cairo 0.8.2.1, and 0.9.0, I can see such changes:

```diff
             "__wrappers__.get_array.Return": {
-                "full_name": "__wrappers__.get_array.Return",
-                "members": {
-                    "pedersen_ptr": {
-                        "cairo_type": "starkware.cairo.common.cairo_builtins.HashBuiltin*",
-                        "offset": 1
-                    },
-                    "range_check_ptr": {
-                        "cairo_type": "felt",
-                        "offset": 2
-                    },
-                    "retdata": {
-                        "cairo_type": "felt*",
-                        "offset": 4
-                    },
-                    "size": {
-                        "cairo_type": "felt",
-                        "offset": 3
-                    },
-                    "syscall_ptr": {
-                        "cairo_type": "felt*",
-                        "offset": 0
-                    }
-                },
-                "size": 5,
-                "type": "struct"
+                "cairo_type": "(syscall_ptr : felt*, pedersen_ptr : starkware.cairo.common.cairo_builtins.HashBuiltin*, range_check_ptr : felt, size : felt, retdata : felt*)",
+                "type": "type_definition"
             },
```
```diff
-                    "ret_struct": {
-                        "cairo_type": "__main__.get_array.Return",
+                    "ret_value": {
+                        "cairo_type": "(arr_len : felt, arr : felt*)",
```
```diff
             "__wrappers__.get_array_encode_return.Return": {
-                "full_name": "__wrappers__.get_array_encode_return.Return",
-                "members": {
-                    "data": {
-                        "cairo_type": "felt*",
-                        "offset": 2
-                    },
-                    "data_len": {
-                        "cairo_type": "felt",
-                        "offset": 1
-                    },
-                    "range_check_ptr": {
-                        "cairo_type": "felt",
-                        "offset": 0
-                    }
-                },
-                "size": 3,
-                "type": "struct"
+                "cairo_type": "(range_check_ptr : felt, data_len : felt, data : felt*)",
+                "type": "type_definition"
             },
```
The return type changes from `struct` to `type_definition`. Not sure it is the actual problem though, just taking notes for everyone.

**Comment by ca11ab1e** [comment] 2022-06-18 18:12
FTR I tested a modified version of the contract that does not touch to the storage var, just to isolate more the behavior. It changes nothing, results are the same.

Contract:
```cairo
%lang starknet

from starkware.cairo.common.alloc import alloc


@external
func get_array() -> (arr_len: felt, arr: felt*):
    const ARRAY_SIZE = 10
    let (ptr) = alloc()
    assert [ptr] = 1
    assert [ptr + 1] = 2
    assert [ptr + 2] = 3
    assert [ptr + 3] = 4
    assert [ptr + 4] = 5
    assert [ptr + 5] = 6
    assert [ptr + 6] = 7
    assert [ptr + 7] = 8
    assert [ptr + 8] = 9
    assert [ptr + 9] = 0
    return (ARRAY_SIZE, ptr)
end
```

**Comment by ca11ab1e** [comment] 2022-06-19 06:50
I was wondering if the return type changes when returning a simple integer: it still return an additional value: `[1 42]` ([tx](https://goerli.voyager.online/tx/0x59c419597888babdc9328f780442222c69c8c0f1d112ccc4e88dbb36e7131f4#events))

Contract (you can play with it [here](https://goerli.voyager.online/contract/0x04764ebed70be65d9ee80e5cb606416e9ce172b3909d84a2d80866b6e070a202#writeContract)):
```cairo
%lang starknet

from starkware.cairo.common.alloc import alloc


@external
func get_array() -> (arr_len : felt, arr : felt*):
    alloc_locals

    let (local arr : felt*) = alloc()
    assert arr[0] = 1
    assert arr[1] = 2
    assert arr[2] = 3

    return (arr_len=3, arr=arr)
end

@external
func get_int() -> (res : felt):
    return (res=42)
end
```

**Comment by FabijanC** [comment] 2022-06-20 07:31
If calling through an account, it is expected behavior to have the first returned value be the length of the return sequence (might depend on account implementation, but I believe they all work that way). Doesn't look like unwanted behavior, I'll be closing this. Tell me if you think it should be reopened.

**Closed by FabijanC** 2022-06-20 07:31 UTC
